name: NPM publish

on:
  release:
    types: [published]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.release.tag_name }}

      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'

      - id: release_tag
        run: |
          if [[ "${PRERELEASE}" == "true" ]]; then
            echo "##[set-output name=tag;]beta"
          else
            echo "##[set-output name=tag;]latest"
          fi
        env:
          PRERELEASE: ${{ github.event.release.prerelease }}

      - run: npm install

      - name: Publish to npm
        run: npm publish --tag ${{ steps.release_tag.outputs.tag }} --access public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
