name: Release

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'

      - name: Verify
        run: |
          npm install
          npm test
          npm run build

  release:
    if: ${{ github.event_name == 'push' }}
    needs: verify
    runs-on: ubuntu-latest

    outputs:
      upload_url: ${{ steps.create-release.outputs.upload_url }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      # Drafts your next Release notes as Pull Requests are merged into "main"
      - name: Create release
        id: create-release
        uses: release-drafter/release-drafter@v5
        with:
          # (Optional) specify config name to use, relative to .github/. Default: release-drafter.yml
          config-name: release-drafter.yaml
          publish: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'

      - name: Update package.json
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          npm version ${{ steps.create-release.outputs.tag_name }}

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish release
        id: publish-release
        uses: release-drafter/release-drafter@v5
        with:
          # (Optional) specify config name to use, relative to .github/. Default: release-drafter.yml
          config-name: release-drafter.yaml
          publish: true
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

  publish-assets:
    if: ${{ github.event_name == 'push' }}
    needs: release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'

      - name: Install pkg
        run: npm install -g pkg

      - name: Build Asset
        run: pkg -o igc --options no-warnings .

      - name: Upload Linux cli
        id: upload-linux-cli
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: ./igc-linux
          asset_name: igc-linux
          asset_content_type: application/octet-stream

      - name: Upload MacOS cli
        id: upload-macos-cli
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: ./igc-macos
          asset_name: igc-macos
          asset_content_type: application/octet-stream
